{% set python_min = '3.11' %}
{% set python_max = '3.12' %}
{% set name = "mosdef-dihedral-fit" %}
{% set version = "0.2.0" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/archive/{{ version }}.tar.gz
  sha256: 725b7f92bb84df9a6f70df5d01e061032e07a1aa9437a747a3fa424b26c44786

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build_number }}

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - netcdf4
    - vmd-python
    - numpy<2
    - mosdef-gomc =1.4.0
    - foyer =0.12.1
    - forcefield-utilities =0.3.0
    - gmso =0.12.4
    - mbuild =0.17.1
    - setuptools <82
    - pytest
    - pytest-cov
    - coverage

test:
  imports:
    - mosdef_dihedral_fit
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  summary: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans
    (RB) torsion.
  description: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans
    (RB) torsion.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  dev_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit

extra:
  recipe-maintainers:
    - bc118
    - daico007
    - CalCraven
