{% set name = "mosdef-dihedral-fit" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/archive/{{ version }}.tar.gz
  sha256: 321272e79b1f86d44eef29b10f296edfd60de9faa9e0d4b4551ec4f898e2f69a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<=3.11
    - pip
  run:
    - python >=3.10,<=3.11
    - vmd-python
    - mosdef-gomc >=1.3.0

test:
  imports:
    - mosdef_dihedral_fit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  summary: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans (RB) torsion.
  description: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans (RB) torsion.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  dev_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit

extra:
  recipe-maintainers:
    - bc118
    - daico007
    - CalCraven
    
